name: git show-ref

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  on_trigger:
    name: On trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git show-ref
        run: git show-ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
